apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-redis-storage
  namespace: gitlab
  annotations:
    volume.beta.kubernetes.io/storage-class: fast
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
